export const services = [
  {
    slug: 'custom-website-design',
    kicker: 'Website Design',
    title: `Custom Website Design`,
    seoTitle: `Custom Website Design for Jacksonville Small Businesses`,
    metaDescription: `Custom-built websites for Jacksonville-area small businesses — no templates, no page builders. Plans starting at $399 to design and launch, from $97/mo for hosting and care.`,
    tagline: `A site built around your business, not a template someone else already used.`,
    intro: [
      `Most "affordable" websites are really a page builder with your logo dropped in — the same layout as a thousand other businesses, just recolored. We design every site from a blank canvas, based on what your business actually does, who your customer is, and what makes you different from the next name in the search results.`,
      `That means real decisions get made about your site instead of defaults getting accepted: what a first-time visitor needs to see in the first five seconds, where the phone number and quote form actually belong, and which of your services deserve their own page versus a shared section.`,
    ],
    included: [
      `A layout designed specifically for your business and customers — not a reused theme`,
      `Copywriting included, so you are not starting from a blank page`,
      `Mobile-first build, since most local searches happen on a phone`,
      `On-page SEO set up correctly from day one — titles, meta descriptions, headings, schema`,
      `A working contact form connected to your email`,
      `Launch on your own domain with hosting included`,
    ],
    whyItMatters: `A generic template can look fine in a screenshot, but it rarely matches how your specific customers actually decide who to call. A roofer's visitor is scanning for urgency and trust in seconds; a boutique's visitor is browsing and comparing. A site built around your actual business gets both the first impression and the conversion path right, instead of forcing your business to fit someone else's layout.`,
    process: [
      { title: 'Discovery call', body: `We talk through your business, your customers, and what your current site (or lack of one) is costing you.` },
      { title: 'Design & copy', body: `You get a real design and real written copy to review — not a placeholder theme with lorem ipsum text.` },
      { title: 'Build, review, launch', body: `We build it, you review it, we adjust it, and it goes live on your domain — typically inside two weeks.` },
    ],
    faq: [
      { q: `How is this different from using Wix or Squarespace myself?`, a: `You are not learning a builder, troubleshooting templates, or writing your own copy. You get a site designed and written for your business, built correctly for SEO, and someone to call when something needs to change — for the same monthly cost as most DIY builder plans.` },
      { q: `Do I own the website?`, a: `Yes. The site is built on your own domain, and it is yours. There is no long-term contract on any plan — your monthly plan covers hosting, security, and ongoing care, and you can cancel anytime.` },
      { q: `How long does it take to launch?`, a: `Most custom builds go from discovery call to live site in about two weeks, depending on how quickly we get content and feedback back and forth.` },
    ],
    relatedBlogSlugs: ['small-business-website-design-guide', 'how-much-does-a-website-cost', 'website-conversion-optimization-tips'],
    relatedServiceSlugs: ['website-redesign-services', 'mobile-responsive-web-design', 'website-copywriting'],
  },
  {
    slug: 'website-redesign-services',
    kicker: 'Website Design',
    title: `Website Redesign Services`,
    seoTitle: `Website Redesign Services | Modernize an Outdated Site`,
    metaDescription: `Redesign an outdated, slow, or hard-to-manage website without losing your search rankings or content. Plans starting at $399, from $97/mo for hosting and care.`,
    tagline: `Keep what's working. Fix everything that isn't.`,
    intro: [
      `An old site rarely needs to be thrown out — it needs to be rebuilt properly. We start by reviewing what you already have: what's ranking in Google, what content is actually useful, and what customers are probably bouncing off of. Then we rebuild around that, instead of starting over from zero and losing ground you've already earned.`,
      `Redesigns are also where we most often find real, fixable problems — broken contact forms nobody noticed, a site that's unreadable on a phone, or pages that haven't reflected your actual services in years.`,
    ],
    included: [
      `A full audit of your current site before anything is rebuilt`,
      `A 301 redirect plan so existing Google rankings and links carry over correctly`,
      `A faster, mobile-first rebuild on modern hosting`,
      `Updated copy, photos, and services that reflect your business today`,
      `Corrected metadata, headings, and schema markup for SEO`,
      `Ongoing hosting and care afterward, so it doesn't go stale again`,
    ],
    whyItMatters: `A redesign done without a migration plan is one of the most common ways small businesses accidentally lose search traffic — old URLs go 404, rankings reset, and nobody notices until leads slow down weeks later. Doing it correctly means your new site can actually start from where your old one left off, rather than starting over.`,
    process: [
      { title: 'Audit', body: `We review your current site's traffic, rankings, structure, and content before touching anything.` },
      { title: 'Rebuild with a migration plan', body: `We design the new site and map every existing URL to its new destination.` },
      { title: 'Launch & monitor', body: `We go live, confirm redirects and rankings are intact, and watch for issues in the first few weeks.` },
    ],
    faq: [
      { q: `Will I lose my Google rankings if I redesign my site?`, a: `Not if it's done correctly. The biggest risk in a redesign is changed URLs with no redirect plan. We map every existing page to its new location with proper 301 redirects before launch.` },
      { q: `Can you keep my existing content?`, a: `Yes — we review what you have and keep anything that's working, updating only what's outdated, unclear, or missing.` },
      { q: `My current site was built on Wix / Squarespace / GoDaddy. Can you still redesign it?`, a: `Yes. We rebuild the site independently on its own hosting, so you're no longer locked into that platform's templates or fees.` },
    ],
    relatedBlogSlugs: ['signs-its-time-for-a-website-redesign', 'website-launch-checklist', 'why-website-speed-matters'],
    relatedServiceSlugs: ['website-migration', 'custom-website-design', 'website-speed-optimization'],
  },
  {
    slug: 'small-business-web-design',
    kicker: 'Website Design',
    title: `Small Business Web Design`,
    seoTitle: `Small Business Web Design | Flat-Rate, No Contracts`,
    metaDescription: `Web design built specifically for small, owner-operated businesses — flat pricing, no long-term contract, and a real person to call when you need a change.`,
    tagline: `Built for owners who'd rather run their business than manage a website.`,
    intro: [
      `Small business owners don't need an enterprise marketing platform — they need a site that answers the phone, so to speak: it shows up in local search, explains what you do clearly, and makes it easy for someone to reach out. That's the entire design brief, and it's exactly what we build.`,
      `We work almost exclusively with small, local, owner-operated businesses across Northeast Florida, which means the process is built around how you actually operate — no marketing jargon, no long onboarding forms, no agency retainer.`,
    ],
    included: [
      `A site sized correctly for a small business — not an over-built platform you'll never fully use`,
      `Plans starting at $399 to design and launch, from $97/mo afterward — no surprise invoices`,
      `No long-term contract; cancel anytime`,
      `Direct access to the person who built your site, not a support ticket queue`,
      `Local SEO basics included from the start`,
      `Room to grow — add pages or services later without a rebuild`,
    ],
    whyItMatters: `A lot of small business owners either overpay for an agency package built for much larger companies, or underinvest in a DIY builder that never quite gets finished. Pricing and process built specifically around a small, local business closes that gap — professional results without enterprise overhead.`,
    process: [
      { title: 'A short discovery call', body: `Usually 20–30 minutes, focused on your business and your customers, not a sales pitch.` },
      { title: 'A clear quote', body: `Starter plans from $399 to build, $97/mo after launch — no hidden add-ons.` },
      { title: 'Live in about two weeks', body: `From first call to launched site is typically a couple of weeks.` },
    ],
    faq: [
      { q: `I'm a one-person business. Is this overkill for me?`, a: `No — this is exactly who it's built for. Sole proprietors and small owner-operated teams make up most of our clients.` },
      { q: `What if my business grows and I need more from my site later?`, a: `Your site can grow with you — new pages, new services, or new sections can be added without starting over.` },
      { q: `Do you only work with businesses in Jacksonville?`, a: `We're based in Jacksonville and work with businesses throughout Northeast Florida, but the process works for any local, service-based business.` },
    ],
    relatedBlogSlugs: ['small-business-website-design-guide', 'do-i-really-need-a-website-in-2026', 'website-roi-for-small-business'],
    relatedServiceSlugs: ['custom-website-design', 'website-care-plan', 'local-seo-services'],
  },
  {
    slug: 'ecommerce-website-design',
    kicker: 'Website Design',
    title: `E-Commerce Website Design`,
    seoTitle: `E-Commerce Website Design for Local Businesses`,
    metaDescription: `Sell products online with a fast, mobile-friendly store built around your catalog — a setup fee based on your plan, then a monthly plan for hosting, security, and support.`,
    tagline: `A store that's fast, easy to update, and actually sells.`,
    intro: [
      `For a local business, an online store usually doesn't need to compete with Amazon — it needs to let existing and nearby customers buy what you already sell without calling or messaging you first. We build lean, fast product catalogs and checkout flows sized to what you actually carry.`,
      `That means a smaller store with 20 products loads just as fast and looks just as professional as one with 2,000 — the build is scaled to your catalog, not a bloated platform you'll spend years growing into.`,
    ],
    included: [
      `A product catalog built around what you actually sell`,
      `Secure checkout with standard payment processing`,
      `Mobile-optimized product pages and cart`,
      `Inventory and pricing you can update yourself, with support if you need it`,
      `SEO-friendly product pages so items can be found in search, not just on your site`,
      `Ongoing hosting, security, and backups included`,
    ],
    whyItMatters: `Cart abandonment is heavily driven by slow load times and confusing checkouts — both fixable at the build stage rather than patched later. A store built correctly from the start converts more of the traffic you're already getting instead of losing it at the last step.`,
    process: [
      { title: 'Catalog & payment setup', body: `We organize your products and connect a secure, standard payment processor.` },
      { title: 'Design & build', body: `Product pages, cart, and checkout are built mobile-first and tested end-to-end.` },
      { title: 'Launch & train', body: `You get a walkthrough of how to add products, update pricing, and manage orders.` },
    ],
    faq: [
      { q: `Can I update products and prices myself?`, a: `Yes — you get access to manage your own catalog, and we're available if you'd rather we make the changes for you.` },
      { q: `What payment processors do you support?`, a: `We set up standard, secure payment processing suited to your product type and order volume during the discovery call.` },
      { q: `Do you handle shipping and tax setup?`, a: `We configure standard shipping rules and tax settings during setup based on how you sell today.` },
    ],
    relatedBlogSlugs: ['website-design-for-cleaning-companies', 'website-conversion-optimization-tips', 'how-much-does-a-website-cost'],
    relatedServiceSlugs: ['custom-website-design', 'website-speed-optimization', 'conversion-rate-optimization'],
  },
  {
    slug: 'landing-page-design',
    kicker: 'Website Design',
    title: `Landing Page Design`,
    seoTitle: `Landing Page Design for Ads & Promotions`,
    metaDescription: `Dedicated landing pages built to convert ad clicks and campaign traffic into calls and leads — fast to launch, easy to update.`,
    tagline: `One offer, one page, one clear next step.`,
    intro: [
      `Sending paid traffic or a promotion to your general homepage almost always underperforms, because a homepage has to serve every visitor and every goal at once. A dedicated landing page exists for one purpose — get a specific visitor, from a specific campaign, to take one specific action.`,
      `We build landing pages that match the message that got someone to click in the first place, strip out unrelated navigation and distractions, and lead to a single clear call to action — call, quote form, or booking.`,
    ],
    included: [
      `A page built around one specific offer or campaign`,
      `Copy and layout matched to the ad or promotion driving traffic`,
      `A single, clear call to action — no competing links`,
      `Fast load times, since paid traffic is unforgiving of slow pages`,
      `Conversion tracking set up so you can see what's working`,
      `Easy to launch alongside your existing site`,
    ],
    whyItMatters: `Every extra link, menu item, or unrelated section on a landing page is a chance for a paying-traffic visitor to leave before converting. A focused page consistently converts a higher percentage of the same traffic than a general homepage does — meaning the same ad budget produces more actual leads.`,
    process: [
      { title: 'Define the offer', body: `We confirm exactly what the page needs to accomplish and for whom.` },
      { title: 'Build & connect tracking', body: `The page is built and connected to Google Analytics so results are measurable.` },
      { title: 'Launch alongside your site', body: `The landing page goes live without disrupting your main website.` },
    ],
    faq: [
      { q: `Do I need a full new website for one campaign?`, a: `No — a landing page can be built and launched on its own, separate from a full site rebuild.` },
      { q: `Can you connect this to my ad campaigns?`, a: `We build the page with tracking in place so you can connect it to whatever ad platform you're running.` },
      { q: `Can I reuse a landing page for future promotions?`, a: `Yes — pages can be updated and reused, or we can build a new one quickly for the next campaign.` },
    ],
    relatedBlogSlugs: ['website-conversion-optimization-tips', 'digital-marketing-strategy-for-local-business'],
    relatedServiceSlugs: ['conversion-rate-optimization', 'google-analytics-setup', 'custom-website-design'],
  },
  {
    slug: 'website-hosting',
    kicker: 'Care Plan',
    title: `Website Hosting`,
    seoTitle: `Website Hosting for Small Businesses | Included, Not Extra`,
    metaDescription: `Fast, secure website hosting included in every Proffit Marketing plan — no separate hosting bill, no surprise renewal fees.`,
    tagline: `One monthly plan. No separate hosting invoice to track.`,
    intro: [
      `A lot of small business owners end up paying three different companies for one website — a builder, a domain registrar, and a hosting company — and juggling renewal dates for each. Hosting is included in every site we build, on modern, fast infrastructure, as part of the same monthly plan that covers your care plan.`,
      `That also means when something needs attention — a certificate renewal, a server issue, a slow-loading page — there's one place to call, not three separate support lines pointing at each other.`,
    ],
    included: [
      `Fast, modern hosting included in your monthly plan`,
      `SSL certificate (the padlock and https) managed for you`,
      `Uptime monitoring so issues are caught early`,
      `Automatic backups`,
      `No separate hosting bill or renewal to track`,
      `One point of contact if anything goes wrong`,
    ],
    whyItMatters: `Slow, unreliable hosting is one of the most common hidden causes of poor Google rankings and lost leads — a fast site that occasionally goes down or times out during a search still loses the customer. Hosting is treated as core infrastructure, not an upsell, which is why it's bundled rather than billed separately.`,
    process: [
      { title: 'Included at launch', body: `Every new site is deployed on the same fast hosting from day one.` },
      { title: 'Monitored continuously', body: `Uptime and performance are checked on an ongoing basis, not just at launch.` },
      { title: 'Backed up automatically', body: `Regular backups mean a fix is always possible if something ever breaks.` },
    ],
    faq: [
      { q: `Do I need to buy hosting separately?`, a: `No — hosting is included in every monthly plan, starting at $97/mo, alongside every site we build.` },
      { q: `What happens if my site goes down?`, a: `Uptime is monitored, and issues are addressed directly — there's no third-party hosting company to file a ticket with.` },
      { q: `Can you host a site you didn't build?`, a: `In most cases yes, after a review — reach out with details about your current site and hosting setup.` },
    ],
    relatedBlogSlugs: ['website-maintenance-checklist', 'why-website-speed-matters'],
    relatedServiceSlugs: ['website-maintenance-plans', 'website-security-backups', 'website-care-plan'],
  },
  {
    slug: 'website-maintenance-plans',
    kicker: 'Care Plan',
    title: `Website Maintenance Plans`,
    seoTitle: `Website Maintenance Plans for Small Businesses`,
    metaDescription: `Ongoing website maintenance — updates, security patches, backups, and small content edits — included starting at $97/mo with every site we build.`,
    tagline: `A website is never really "done." Ours don't get left behind.`,
    intro: [
      `A site that isn't maintained slowly drifts out of date — software gets outdated, small errors go unnoticed, and content stops reflecting the business. Maintenance is built into every plan rather than sold as an occasional emergency service, so small issues get caught before they turn into a redesign.`,
      `That also covers the small, ongoing changes every business needs — updating hours, adding a new service, swapping a photo — without needing a developer or a new invoice every time.`,
    ],
    included: [
      `Regular software and security updates`,
      `Small content edits included — hours, pricing, photos, text changes`,
      `Monitoring for broken links, forms, or errors`,
      `Monthly SEO and analytics review`,
      `Direct access to request changes, not a ticket system`,
      `No separate invoice for routine maintenance`,
    ],
    whyItMatters: `Sites that go untouched for a year or more are far more likely to have outdated information, broken forms nobody noticed, or security vulnerabilities — all of which quietly cost leads. Ongoing maintenance catches these before a customer does.`,
    process: [
      { title: 'Included from launch', body: `Maintenance starts the day your site goes live, not after something breaks.` },
      { title: 'Routine checks', body: `Forms, links, speed, and security are checked on an ongoing basis.` },
      { title: 'Fast small edits', body: `Need something updated? Just reach out — most small edits are handled quickly.` },
    ],
    faq: [
      { q: `What counts as a "small edit"?`, a: `Things like updating hours, adding a photo, changing pricing, or editing a paragraph of text — the everyday changes a business needs.` },
      { q: `Is there a limit to how many changes I can request?`, a: `The plan is built for reasonable, ongoing small edits — for larger changes like new pages or a redesign, we'll scope it separately.` },
      { q: `What if I stop paying the monthly plan?`, a: `You can cancel anytime, but maintenance, hosting, and support are only included while the plan is active.` },
    ],
    relatedBlogSlugs: ['website-maintenance-checklist', 'website-launch-checklist'],
    relatedServiceSlugs: ['website-hosting', 'website-security-backups', 'website-care-plan'],
  },
  {
    slug: 'website-speed-optimization',
    kicker: 'Technical SEO',
    title: `Website Speed Optimization`,
    seoTitle: `Website Speed Optimization | Faster Load Times, Better Rankings`,
    metaDescription: `Speed up a slow website with image optimization, modern hosting, and Core Web Vitals fixes — built in from the start or added to an existing site.`,
    tagline: `Every extra second of load time is customers leaving before they see anything.`,
    intro: [
      `Page speed affects two things at once: how many visitors actually stay long enough to read your site, and how Google evaluates your pages for ranking through Core Web Vitals. Both are addressed directly — through image optimization, efficient code, and fast hosting — rather than left as an afterthought.`,
      `On new builds, speed is handled from the first line of code. On existing sites, we run a review to find the specific things slowing a page down — usually oversized images, unnecessary scripts, or slow hosting — and fix them directly.`,
    ],
    included: [
      `Image compression and modern formats (WebP) instead of oversized files`,
      `Removal of unnecessary scripts and bloat`,
      `Fast, modern hosting instead of shared, overloaded servers`,
      `Core Web Vitals review (loading, interactivity, visual stability)`,
      `Mobile load-time testing, not just desktop`,
      `A clear before/after comparison of load times`,
    ],
    whyItMatters: `Google has confirmed page experience and Core Web Vitals are a ranking factor, and independent studies consistently show conversion rates drop sharply as load time increases past a couple of seconds. A slow site is losing both search visibility and visitors who already found it.`,
    process: [
      { title: 'Speed audit', body: `We test your current site's load time and identify exactly what's slowing it down.` },
      { title: 'Targeted fixes', body: `Images, scripts, and hosting are addressed based on what the audit actually found.` },
      { title: 'Re-test & confirm', body: `We re-test after the fixes to confirm the improvement is real, not assumed.` },
    ],
    faq: [
      { q: `My site feels fine to me — why would it be slow?`, a: `Sites often feel fine on the machine and connection they were built on, but load noticeably slower on an average mobile connection — which is where most local searches happen.` },
      { q: `Will faster load times actually improve my Google ranking?`, a: `Speed and page experience are a confirmed ranking factor, though not the only one. It's one of several levers alongside content quality and backlinks.` },
      { q: `Can you fix this on a site you didn't build?`, a: `In many cases yes — we review the existing site first and confirm what's fixable within its current platform.` },
    ],
    relatedBlogSlugs: ['why-website-speed-matters', 'website-conversion-optimization-tips'],
    relatedServiceSlugs: ['website-hosting', 'conversion-rate-optimization', 'website-redesign-services'],
  },
  {
    slug: 'local-seo-services',
    kicker: 'SEO',
    title: `Local SEO Services`,
    seoTitle: `Local SEO Services for Jacksonville-Area Businesses`,
    metaDescription: `Local SEO built into every website and care plan — on-page optimization, Google Business Profile alignment, and city-specific content for Northeast Florida businesses.`,
    tagline: `Show up when nearby customers search for what you do.`,
    intro: [
      `Local SEO is the set of signals that determine whether your business shows up when someone nearby searches "[service] near me" or "[service] in [city]." It's built into every site from the start — correct on-page structure, consistent business information, and content that actually matches how local customers search — rather than sold as a separate add-on later.`,
      `For businesses that want to go further, we also build dedicated location and service content, and help align your Google Business Profile with your website so both are reinforcing the same information.`,
    ],
    included: [
      `On-page SEO set up correctly on every page — titles, headings, meta descriptions`,
      `Consistent business name, address, and phone number (NAP) across your site`,
      `LocalBusiness structured data (schema) so Google understands your service area`,
      `Location and service page strategy for the areas you actually serve`,
      `Guidance on aligning your Google Business Profile with your website`,
      `Monthly SEO review included in your care plan`,
    ],
    whyItMatters: `Local search results are ranked heavily on relevance, distance, and prominence — and prominence is built through consistent, accurate information repeated across your website, your Google Business Profile, and outside citations. Getting the on-site half right is the foundation everything else builds on.`,
    process: [
      { title: 'On-page foundation', body: `Every page is structured and written with the local searches you actually want to rank for in mind.` },
      { title: 'Structured data & consistency', body: `Schema markup and consistent NAP information reinforce your service area to Google.` },
      { title: 'Ongoing review', body: `Local SEO is checked as part of your monthly care plan, not set once and forgotten.` },
    ],
    faq: [
      { q: `Is local SEO included, or is it a separate service?`, a: `On-page local SEO is included in every website we build and in every monthly care plan. Growth and Authority plans add advanced local SEO and Google Business Profile work on top of the basics.` },
      { q: `Do you also help with my Google Business Profile?`, a: `Yes — we can review and advise on your GBP setup so it's consistent with your website and optimized for your service area.` },
      { q: `How long does local SEO take to show results?`, a: `Local SEO is gradual — most businesses see meaningful movement over a few months, not days, as Google builds confidence in your site and listing.` },
    ],
    relatedBlogSlugs: ['local-seo-guide-for-small-businesses', 'google-business-profile-optimization-guide', 'seo-basics-for-small-business-owners'],
    relatedServiceSlugs: ['google-business-profile-management', 'custom-website-design', 'conversion-rate-optimization'],
  },
  {
    slug: 'google-business-profile-management',
    kicker: 'SEO',
    title: `Google Business Profile Management`,
    seoTitle: `Google Business Profile Management & Optimization`,
    metaDescription: `Get your Google Business Profile fully optimized — categories, services, photos, posts, and Q&A — to compete for the local map pack.`,
    tagline: `Your Google Business Profile is often a customer's very first impression.`,
    intro: [
      `For most local searches, a Google Business Profile shows up before your website does — the map pack, the reviews, the photos, the hours. It deserves the same attention as your website, but it's the piece most small business owners set up once and never touch again.`,
      `We review your existing profile against what's actually available — categories, services, products, posts, photos, and Q&A — and either optimize it directly or hand you exactly what to change.`,
    ],
    included: [
      `Primary and secondary category review`,
      `Full services and products list built out, not left blank`,
      `Business description rewritten in the language customers actually search with`,
      `A posting cadence plan so your profile stays active`,
      `Photo and Q&A recommendations`,
      `Guidance on responding to reviews to build trust and rankings`,
    ],
    whyItMatters: `Google explicitly favors profiles that are complete, active, and well-reviewed for map pack placement over ones that are technically claimed but mostly empty. A fully built-out profile with recent posts and photos consistently outperforms a bare-bones listing in the same category and location.`,
    process: [
      { title: 'Full profile audit', body: `We review every section of your current listing against what's actually available to fill in.` },
      { title: 'Optimization plan', body: `You get exactly what to change — categories, description, services, photos, posts.` },
      { title: 'Ongoing activity', body: `We help you build a simple, sustainable posting habit so the profile stays active.` },
    ],
    faq: [
      { q: `Can you post directly to my Google Business Profile?`, a: `Google requires the business owner to manage their own listing directly. We provide exact, ready-to-paste content and guidance for every section.` },
      { q: `Why does my competitor rank above me with fewer reviews?`, a: `Ranking in the map pack depends on relevance, distance, and prominence together — a fully completed, active, well-categorized profile can outrank a less-optimized one with more reviews.` },
      { q: `How often should I post updates?`, a: `Roughly every one to two weeks is enough to keep a profile looking active without becoming a burden.` },
    ],
    relatedBlogSlugs: ['google-business-profile-optimization-guide', 'local-seo-guide-for-small-businesses'],
    relatedServiceSlugs: ['local-seo-services', 'conversion-rate-optimization'],
  },
  {
    slug: 'website-security-backups',
    kicker: 'Care Plan',
    title: `Website Security & Backups`,
    seoTitle: `Website Security & Backups for Small Business Sites`,
    metaDescription: `Ongoing security monitoring and automatic backups included with every website — so a hack, plugin issue, or mistake never means starting over.`,
    tagline: `If something ever goes wrong, there's always a way back.`,
    intro: [
      `A website going down, getting hacked, or losing content is rare, but it's expensive when it happens without a backup — sometimes meaning a full rebuild. Security monitoring and automatic backups are included in every plan, not sold as emergency recovery after the fact.`,
      `This runs quietly in the background: certificates stay current, software stays patched, and a recent backup always exists — so the worst case is a quick restore, not a rebuild from scratch.`,
    ],
    included: [
      `SSL certificate management (the padlock / https)`,
      `Regular automatic backups`,
      `Security monitoring for suspicious activity`,
      `Software and plugin updates kept current`,
      `A restore plan if something ever does go wrong`,
      `Included in every monthly care plan — no separate security invoice`,
    ],
    whyItMatters: `Outdated software and unpatched plugins are the most common way small business sites get compromised, and a hacked or defaced site can also trigger Google security warnings that scare away visitors and hurt rankings. Preventing that quietly is far cheaper than recovering from it.`,
    process: [
      { title: 'Baseline setup', body: `Every site launches with current, secure software and an SSL certificate.` },
      { title: 'Ongoing monitoring', body: `Updates and monitoring run continuously as part of your care plan.` },
      { title: 'Backups on a schedule', body: `Regular backups mean a recent, restorable version always exists.` },
    ],
    faq: [
      { q: `What happens if my site does get hacked?`, a: `With a recent backup in place, the fastest fix is usually a restore to the last clean version rather than a rebuild.` },
      { q: `Is security really necessary for a small local business site?`, a: `Yes — most attacks target outdated software indiscriminately, not specific businesses, so any unpatched site is a potential target regardless of size.` },
      { q: `Do I need to do anything myself?`, a: `No — monitoring, updates, and backups are handled as part of your monthly plan.` },
    ],
    relatedBlogSlugs: ['website-maintenance-checklist', 'website-launch-checklist'],
    relatedServiceSlugs: ['website-hosting', 'website-maintenance-plans', 'website-care-plan'],
  },
  {
    slug: 'mobile-responsive-web-design',
    kicker: 'Website Design',
    title: `Mobile-Responsive Web Design`,
    seoTitle: `Mobile-Responsive Web Design | Built Phone-First`,
    metaDescription: `Websites designed phone-first, since most local searches happen on mobile — tested across real devices, not just resized in a browser.`,
    tagline: `Designed for a phone first. Everything else follows from there.`,
    intro: [
      `Most local searches — and nearly all "near me" searches — happen on a phone, not a desktop. Every site is designed starting from the mobile layout, then adapted up to tablet and desktop, rather than designed for a big screen and shrunk down afterward.`,
      `That distinction matters more than it sounds: text sizes, tap targets, menu behavior, and form fields all behave differently when designed mobile-first versus retrofitted, and it shows in how easily a visitor can actually find your phone number and act.`,
    ],
    included: [
      `Mobile-first design and build process`,
      `Tap targets and menus sized correctly for real thumbs, not a mouse cursor`,
      `Click-to-call phone numbers and simplified mobile forms`,
      `Testing across real phone and tablet sizes, not just a resized browser window`,
      `Fast mobile load times, since mobile connections are less forgiving`,
      `The same design quality on mobile as on desktop — not a stripped-down version`,
    ],
    whyItMatters: `Google evaluates the mobile version of your site for ranking purposes by default (mobile-first indexing), and a majority of local traffic arrives on a phone. A site that merely "resizes" on mobile without being genuinely designed for it usually shows the cracks exactly where a customer is trying to call you.`,
    process: [
      { title: 'Design mobile-first', body: `Layouts are designed for a phone screen from the very first draft.` },
      { title: 'Adapt upward', body: `The design then expands cleanly to tablet and desktop sizes.` },
      { title: 'Real-device testing', body: `We test on actual phones and tablets before launch, not just a resized browser.` },
    ],
    faq: [
      { q: `Isn't every modern website already mobile-friendly?`, a: `Most are technically responsive, but far fewer are actually designed mobile-first — meaning the mobile experience is often an afterthought rather than the starting point.` },
      { q: `Does mobile design affect my Google ranking?`, a: `Yes — Google primarily uses the mobile version of your site for indexing and ranking, so a poor mobile experience can directly affect visibility.` },
      { q: `Can you fix mobile issues on my existing site without a full redesign?`, a: `In many cases, yes — reach out with your current site and we'll review what's fixable versus what needs a rebuild.` },
    ],
    relatedBlogSlugs: ['why-website-speed-matters', 'website-conversion-optimization-tips'],
    relatedServiceSlugs: ['custom-website-design', 'website-speed-optimization', 'landing-page-design'],
  },
  {
    slug: 'website-copywriting',
    kicker: 'Content',
    title: `Website Copywriting`,
    seoTitle: `Website Copywriting Services for Small Businesses`,
    metaDescription: `Clear, persuasive website copy written around your actual business and customers — included with every site, or available for an existing site.`,
    tagline: `The words on your site decide whether someone calls or clicks away.`,
    intro: [
      `Design gets someone to stay on a page for a few seconds. Copy is what actually convinces them to call, quote, or book — and it's included with every site we build rather than left for the business owner to write themselves under deadline pressure.`,
      `We write from the discovery call, not a generic template: what you actually do, who your best customers are, what they usually ask before hiring you, and what makes your business different from the next search result.`,
    ],
    included: [
      `Homepage and service page copy written around your real business`,
      `Clear calls to action instead of vague "learn more" links`,
      `FAQ content addressing what customers actually ask before hiring`,
      `SEO-aware writing that reads naturally, not keyword-stuffed`,
      `A tone that matches your business — professional trades, friendly local shop, or anywhere between`,
      `Revisions included until the copy actually sounds right to you`,
    ],
    whyItMatters: `Vague, generic copy ("Welcome to our website! We are committed to excellence...") tells a visitor nothing and gives Google little to match against real searches. Specific, clear copy about what you actually do and where you do it helps both the customer deciding whether to call and the search engine deciding whether to show you.`,
    process: [
      { title: 'Discovery call', body: `We learn about your business directly rather than guessing from a questionnaire.` },
      { title: 'First draft', body: `You receive real copy to react to, not a placeholder to fill in yourself.` },
      { title: 'Revise together', body: `We adjust tone and details until it actually sounds like your business.` },
    ],
    faq: [
      { q: `Do I have to write my own website copy?`, a: `No — copywriting is included with every site we build.` },
      { q: `What if I already have copy I like from my old site?`, a: `We're happy to keep and refine existing copy that's working rather than replace it just to replace it.` },
      { q: `Can you write copy for just one page of my existing site?`, a: `Yes — reach out with the details and we can scope a smaller copywriting project.` },
    ],
    relatedBlogSlugs: ['digital-marketing-strategy-for-local-business', 'what-makes-a-website-trustworthy'],
    relatedServiceSlugs: ['custom-website-design', 'logo-and-branding', 'conversion-rate-optimization'],
  },
  {
    slug: 'logo-and-branding',
    kicker: 'Content',
    title: `Logo & Brand Identity Design`,
    seoTitle: `Logo & Brand Identity Design for Small Businesses`,
    metaDescription: `Simple, professional logo and brand identity design — colors, fonts, and a mark that looks credible on a website, a truck, or a business card.`,
    tagline: `A brand that looks credible everywhere it shows up.`,
    intro: [
      `A logo doesn't need to be complicated to work — it needs to look intentional, read clearly at a small size, and hold up on a website, a vehicle wrap, or a business card equally well. We design straightforward, professional marks rather than over-designed logos that look great on a poster and fall apart everywhere else.`,
      `This is often paired with a new website build, so the logo, colors, and fonts are consistent from the very start rather than retrofitted onto a site after the fact.`,
    ],
    included: [
      `A logo mark designed to work at both large and small sizes`,
      `A simple, consistent color palette for your brand`,
      `Font choices that carry across your website and printed materials`,
      `Files ready for both web and print use`,
      `Consistency built directly into your new website design`,
      `Guidance on where and how to use your brand consistently`,
    ],
    whyItMatters: `Inconsistent branding — a different logo on your truck than on your website, or colors that don't match between your Google Business Profile and your site — subtly signals a less established, less trustworthy business, even when the work itself is excellent. A consistent, simple brand builds credibility before a customer reads a single word.`,
    process: [
      { title: 'Discovery', body: `We talk through your business, your customers, and what feels right (and wrong) about your current look.` },
      { title: 'Concepts', body: `You review real logo and color concepts, not abstract mood boards.` },
      { title: 'Finalize & apply', body: `The final brand is applied consistently across your new website and provided for other uses.` },
    ],
    faq: [
      { q: `I already have a logo I like. Can you just build the website around it?`, a: `Yes — we can build your site to match an existing logo and brand rather than replace it.` },
      { q: `Do I get the logo files to use elsewhere, like on a truck or business cards?`, a: `Yes — you receive files suitable for both web and print use.` },
      { q: `Is branding included with a new website, or a separate cost?`, a: `Light brand refinement is often included as part of a new site build; a full brand identity project can be scoped separately if needed.` },
    ],
    relatedBlogSlugs: ['what-makes-a-website-trustworthy', 'small-business-website-design-guide'],
    relatedServiceSlugs: ['website-copywriting', 'custom-website-design'],
  },
  {
    slug: 'conversion-rate-optimization',
    kicker: 'Growth',
    title: `Conversion Rate Optimization`,
    seoTitle: `Conversion Rate Optimization for Local Business Websites`,
    metaDescription: `Turn more of your existing website traffic into calls and quote requests — reviewed calls-to-action, trust signals, forms, and page layout.`,
    tagline: `Before spending more on traffic, get more out of the traffic you already have.`,
    intro: [
      `It's common for a small business to invest in ads or SEO to drive more visitors to a site that's quietly losing most of them — a buried phone number, a confusing form, or a page with no clear next step. Conversion review looks at what's actually happening on your existing pages and fixes what's costing you leads before anything else.`,
      `This isn't guesswork — it's a structured review of your calls to action, trust signals, page layout, and forms against what's known to help or hurt conversion for local, service-based businesses.`,
    ],
    included: [
      `A full review of your calls to action and where they're placed`,
      `Trust signal audit — reviews, credentials, guarantees, real photos`,
      `Form review — length, fields, and friction points`,
      `Mobile experience review, since most visitors are on a phone`,
      `Specific, prioritized recommendations, not generic best practices`,
      `Implementation of the fixes, not just a list of suggestions`,
    ],
    whyItMatters: `Doubling your traffic and doubling your conversion rate have the same effect on leads — but improving conversion on your existing site is usually far cheaper than doubling ad spend or waiting for SEO to compound. It's often the highest-leverage, lowest-cost improvement available to a local business.`,
    process: [
      { title: 'Review', body: `We go through your site the way an unfamiliar visitor would, noting every point of friction or confusion.` },
      { title: 'Prioritize', body: `Findings are ranked by expected impact, not just listed in the order we found them.` },
      { title: 'Fix', body: `We implement the changes directly rather than leaving you a to-do list.` },
    ],
    faq: [
      { q: `My traffic is fine, but leads are low. Is this what I need?`, a: `Yes — that's the exact pattern conversion review is built to address.` },
      { q: `Do you need access to my analytics to do this?`, a: `It helps, but isn't required — a structured review of the site itself catches most major issues even without analytics access.` },
      { q: `Is this a one-time project or ongoing?`, a: `It can be either — a focused one-time review, or an ongoing part of your monthly care plan.` },
    ],
    relatedBlogSlugs: ['website-conversion-optimization-tips', 'what-makes-a-website-trustworthy'],
    relatedServiceSlugs: ['google-analytics-setup', 'landing-page-design', 'website-copywriting'],
  },
  {
    slug: 'google-analytics-setup',
    kicker: 'Growth',
    title: `Google Analytics & Tracking Setup`,
    seoTitle: `Google Analytics & Conversion Tracking Setup`,
    metaDescription: `Proper Google Analytics 4 and conversion tracking setup, so you can actually see where your leads are coming from — included with every site.`,
    tagline: `You can't improve what you can't measure.`,
    intro: [
      `A surprising number of small business websites either have no analytics installed at all, or have it installed incorrectly so the numbers don't mean anything. Every site is set up with Google Analytics 4 and basic conversion tracking from launch, so you have a real, accurate picture of your traffic from day one.`,
      `Beyond installation, we make sure the events that actually matter — form submissions, phone number clicks, quote requests — are tracked as conversions, not just page views.`,
    ],
    included: [
      `Google Analytics 4 installed correctly sitewide`,
      `Conversion tracking on your contact form and phone number clicks`,
      `A simple explanation of what to actually look at, not just a dashboard dump`,
      `Traffic source tracking, so you know what's actually working`,
      `Monthly review included as part of your care plan`,
      `Setup that survives a redesign or migration, rather than being lost`,
    ],
    whyItMatters: `Without accurate tracking, it's impossible to tell whether a marketing effort — a new blog post, a Google Business Profile change, an ad campaign — actually produced leads or not. Correct analytics turns "I think this is working" into an actual answer.`,
    process: [
      { title: 'Install correctly', body: `Google Analytics 4 is installed and verified across every page.` },
      { title: 'Track what matters', body: `Form submissions and phone clicks are set up as tracked conversions.` },
      { title: 'Review monthly', body: `We help you understand the numbers that actually matter, not just traffic totals.` },
    ],
    faq: [
      { q: `I already have Google Analytics installed. Do I need this?`, a: `It's worth a quick review — many installs are missing conversion tracking even when the base analytics code is present.` },
      { q: `Do I need to understand analytics myself?`, a: `No — we review the numbers with you monthly and highlight what actually matters.` },
      { q: `Does this include Google Ads tracking too?`, a: `Base conversion tracking can be extended to Google Ads if you're running paid campaigns — let us know during setup.` },
    ],
    relatedBlogSlugs: ['website-roi-for-small-business', 'digital-marketing-strategy-for-local-business'],
    relatedServiceSlugs: ['conversion-rate-optimization', 'landing-page-design'],
  },
  {
    slug: 'domain-and-email-setup',
    kicker: 'Care Plan',
    title: `Domain & Business Email Setup`,
    seoTitle: `Domain & Business Email Setup for Small Businesses`,
    metaDescription: `Get a proper business domain and a professional @yourbusiness.com email address set up correctly — no more @gmail for a real business.`,
    tagline: `yourname@yourbusiness.com looks like a real business. yourname@gmail.com doesn't.`,
    intro: [
      `A surprising number of otherwise professional small businesses are still running on a personal Gmail or Yahoo address, which quietly undercuts the trust a good website is trying to build. Getting a domain and professional email set up correctly is a small, one-time task that makes a lasting difference.`,
      `We handle the registration, DNS configuration, and email setup so it works correctly the first time — no half-configured domains pointing nowhere, and no email that silently stops delivering.`,
    ],
    included: [
      `Domain registration or transfer handled correctly`,
      `DNS configured so your website and email both work reliably`,
      `Professional @yourbusiness.com email address setup`,
      `Guidance on accessing your new email on your phone and computer`,
      `Renewal reminders so your domain never accidentally lapses`,
      `One point of contact if anything needs adjusting later`,
    ],
    whyItMatters: `A lapsed domain or broken email can quietly take down your entire online presence and any leads sent to it, often without anyone noticing until a customer mentions their email bounced. Correct setup up front — and someone watching renewal dates — prevents that entirely.`,
    process: [
      { title: 'Domain setup', body: `We register or transfer your domain and configure it correctly.` },
      { title: 'Email configured', body: `Your professional email address is set up and connected to your devices.` },
      { title: 'Ongoing management', body: `Renewals and DNS are monitored as part of your care plan.` },
    ],
    faq: [
      { q: `I already own a domain. Can you just set up email on it?`, a: `Yes — we can configure email on a domain you already own without needing to move anything else.` },
      { q: `Will this affect my existing email or contacts?`, a: `No — we configure new business email carefully so it doesn't disrupt anything you're already using.` },
      { q: `What if my domain is about to expire?`, a: `Let us know as soon as possible — we can help renew it before it lapses and causes downtime.` },
    ],
    relatedBlogSlugs: ['website-launch-checklist', 'what-is-a-sitemap-and-why-it-matters'],
    relatedServiceSlugs: ['website-migration', 'website-hosting'],
  },
  {
    slug: 'website-migration',
    kicker: 'Website Design',
    title: `Website Migration`,
    seoTitle: `Website Migration Services | Switch Platforms Without Losing Rankings`,
    metaDescription: `Move off Wix, Squarespace, GoDaddy, or another agency's platform without losing your content, domain, or Google rankings.`,
    tagline: `Switch platforms without starting your search rankings over.`,
    intro: [
      `Business owners often stay on a website platform they've outgrown — an expensive agency contract, a DIY builder they're tired of — simply because moving feels risky. Done correctly, migrating your domain, content, and rankings to a new, better-built site carries far less risk than most owners expect.`,
      `We review what you currently have, keep your domain and any content that's working, and rebuild the site properly with a redirect plan so search engines and existing links transfer over correctly.`,
    ],
    included: [
      `A full review of your current site before migrating anything`,
      `Your domain moved and configured correctly, with no downtime`,
      `Existing content and rankings preserved through a proper 301 redirect plan`,
      `A rebuilt site on faster, more reliable infrastructure`,
      `Cancellation guidance for your previous platform or agency, if needed`,
      `Ongoing hosting and care afterward, so you're not migrating again in a year`,
    ],
    whyItMatters: `The single biggest risk in switching platforms is losing existing Google rankings because URLs change with no redirect plan in place — this is avoidable with proper planning, but it's the step most DIY migrations skip. Getting it right means the switch is a clean upgrade, not a step backward.`,
    process: [
      { title: 'Review your current site', body: `We document what exists, what's ranking, and what needs to carry over.` },
      { title: 'Rebuild & map redirects', body: `The new site is built while every existing URL is mapped to its new home.` },
      { title: 'Cut over with zero downtime', body: `Your domain is pointed to the new site with redirects live from day one.` },
    ],
    faq: [
      { q: `I'm locked into a contract with my current provider. Can you still help?`, a: `We can plan the migration around your contract timeline so it's ready to launch the moment you're free to switch.` },
      { q: `Will I lose my current search rankings?`, a: `Not if it's planned correctly — proper redirects are the key step that prevents ranking loss during a migration.` },
      { q: `Do I get to keep my domain name?`, a: `Yes — your domain moves with you and continues to belong to you.` },
    ],
    relatedBlogSlugs: ['signs-its-time-for-a-website-redesign', 'website-launch-checklist'],
    relatedServiceSlugs: ['website-redesign-services', 'domain-and-email-setup'],
  },
  {
    slug: 'contact-form-lead-capture',
    kicker: 'Growth',
    title: `Lead Capture & Contact Form Design`,
    seoTitle: `Lead Capture & Contact Form Design for Local Businesses`,
    metaDescription: `Contact forms and lead capture built to actually get submitted — the right fields, the right placement, and delivery straight to your inbox.`,
    tagline: `The form is the whole point. It has to actually work.`,
    intro: [
      `Every other part of a website exists to lead to one moment — a visitor filling out a form or picking up the phone. A form that's too long, buried at the bottom of the page, or simply broken quietly costs leads that never get noticed as lost, because there's no error message, just silence.`,
      `Every form is tested end-to-end before launch, kept short enough that visitors actually finish it, and delivered directly to your email so nothing sits unread in a dashboard you never check.`,
    ],
    included: [
      `Forms placed where visitors actually look for them, not just at the bottom`,
      `Only the fields you actually need — shorter forms convert better`,
      `Instant email delivery of every submission`,
      `Mobile-friendly form fields, tested on real devices`,
      `Spam filtering, so your inbox isn't buried in junk submissions`,
      `Confirmation messaging so visitors know their request went through`,
    ],
    whyItMatters: `A broken or overly long form is one of the most common, least visible sources of lost leads on a small business site — traffic arrives, but conversions quietly don't happen, and it's rarely investigated because there's no visible error. Getting this right is one of the highest-leverage, lowest-cost fixes available.`,
    process: [
      { title: 'Design the right form', body: `We decide exactly which fields are actually necessary for your business.` },
      { title: 'Build & connect', body: `The form is built, connected to your email, and spam-filtered.` },
      { title: 'Test end-to-end', body: `We submit real test entries before launch to confirm delivery works.` },
    ],
    faq: [
      { q: `Where do form submissions go?`, a: `Directly to your email inbox, so nothing sits unnoticed in a separate dashboard.` },
      { q: `Can you check if my current form is actually working?`, a: `Yes — reach out and we can test your existing form and confirm whether submissions are actually being delivered.` },
      { q: `Can I have more than one form on my site?`, a: `Yes — different pages can have different, purpose-built forms if that fits your business.` },
    ],
    relatedBlogSlugs: ['website-conversion-optimization-tips', 'website-launch-checklist'],
    relatedServiceSlugs: ['conversion-rate-optimization', 'landing-page-design'],
  },
  {
    slug: 'website-care-plan',
    kicker: 'Care Plan',
    title: `Website Care Plan`,
    seoTitle: `Website Care Plan | Hosting, Security & Support from $97/mo`,
    metaDescription: `Monthly plans that cover hosting, security, backups, maintenance, and small edits — so your website never quietly goes stale. Starting at $97/mo.`,
    tagline: `Everything a website needs after launch, built into every plan.`,
    intro: [
      `Launching a website is the easy part — keeping it fast, secure, current, and actually generating leads over time is where most small business sites quietly fall behind. Ongoing care is bundled into every plan we offer, starting at $97/mo, instead of leaving you to piece it together across different vendors.`,
      `This is the plan every site we build runs on: hosting, security, backups, small content edits, and a monthly SEO and analytics check-in are included on Starter, with Growth and Authority adding deeper SEO, content, and lead-generation work on top — all handled without a separate invoice for each.`,
    ],
    included: [
      `Fast, secure hosting`,
      `SSL certificate management`,
      `Automatic backups`,
      `Security monitoring and software updates`,
      `Small content edits included`,
      `Monthly SEO and analytics review`,
    ],
    whyItMatters: `A website is closer to a piece of ongoing infrastructure than a one-time purchase — it needs monitoring, updates, and small adjustments the same way a storefront needs upkeep. Bundling that into a predictable monthly plan means it actually happens, instead of being postponed until something breaks.`,
    process: [
      { title: 'Starts at launch', body: `Your care plan begins the moment your site goes live.` },
      { title: 'Runs quietly in the background', body: `Hosting, security, and backups are handled without you needing to think about them.` },
      { title: 'You just ask for changes', body: `Need something updated? Reach out directly — no ticket system, no separate invoice.` },
    ],
    faq: [
      { q: `What exactly is included in each plan?`, a: `Every plan includes hosting, SSL, backups, security monitoring, software updates, small content edits, and a monthly SEO/analytics review. Growth adds advanced SEO, Google Business Profile work, and lead tracking; Authority adds ongoing content, review generation, and conversion optimization. See the full pricing breakdown on our homepage.` },
      { q: `Is there a contract?`, a: `No — every plan is month-to-month, and you can cancel anytime.` },
      { q: `What happens to my site if I cancel?`, a: `The site itself remains yours; hosting, security, and support are tied to an active plan, so you'd need alternative hosting arranged if you cancel.` },
    ],
    relatedBlogSlugs: ['website-maintenance-checklist', 'website-roi-for-small-business'],
    relatedServiceSlugs: ['website-hosting', 'website-maintenance-plans', 'website-security-backups'],
  },
];
